services:
  db:
    image: postgis/postgis:15-3.3-alpine
    platform: linux/amd64
    environment:
      POSTGRES_USER: map_user
      POSTGRES_PASSWORD: kjhkjh
      POSTGRES_DB: map_db
    ports:
      - "55432:5432"
    volumes:
      - ./server/db/initdb:/docker-entrypoint-initdb.d
      - ./server/db/pgdata:/var/lib/postgresql/data
    networks:
      - map_network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    environment:
      - DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    networks:
      - map_network
    depends_on:
      - db
    volumes:
      - ./server/log_handling/logs:/usr/src/app/server/log_handling/logs


  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3009:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - map_network
    depends_on:
    - backend

networks:
  map_network:
